### ISSUE TITLE
Allow FileBundle in ElectrodeContact:relatedRecording

### ISSUE THREAD

**Issue by apdavison** [openMetadataInitiative/openMINDS_SANDS#107]
Some electrophysiology file formats split recordings across multiple files in a common directory. In this scenario, the `relatedRecording` should link to a `FileBundle` rather than a `FileInstance`.

**Comment by lzehl** [comment]
@apdavison yes, I agree. I'll add it asap.

**Comment by UlrikeS91** [comment]
@apdavison and @lzehl, would this apply to `relatedStimulation` too? I can create a PR with the changes (for both or only the `relatedRecording` dependent on the answer to my question.

**Comment by lzehl** [comment]
@UlrikeS91 yes. Please go ahead with a PR and allow for relatedStimulation and relatedRecording FileInstance AND FileBundles to be linked.
