### ISSUE TITLE
Change "atlasTerminology" to "parcellationTerminology"

### ISSUE THREAD

**Issue by UlrikeS91** [openMetadataInitiative/openMINDS_SANDS#112]
Based on a discussion with @lzehl and @tgbugs, e.g. Brodmann areas should not be captured as "atlas terminologies" because the Brodmann descriptions aren't an actual atlas. Parcellation terminology would include such cases. 

(@aeidi89 FYI)

**Comment by lzehl** [comment]
@UlrikeS91 thanks for immediately putting it in. Do you want to take over the PR or should I do it?

**Comment by UlrikeS91** [comment]
I can do it tomorrow :)

**Comment by lzehl** [comment]
was solved in #114
