### ISSUE TITLE
Renaming WHSSD PEV instances with identical hasParent name

### ISSUE THREAD

**Issue by MaaikevS** [openMetadataInitiative/openMINDS_SANDS#168]
This issue arises from pull request #164 

Some PEV names have a parent with the same name, e.g. spinal cord, anterior commisure, facial nerve, medial lemniscus etc.

In later versions these PEV names were typically changed, so now the question is if we should enforce those changes retrospecitively and correct the earlier versions based on this naming conventions. Any thoughts? @UlrikeS91 @aeidi89

**Comment by UlrikeS91** [comment]
Thanks for raising this issue. I'm not sure what the best practice would be. My concerns are that users may mistake the ParcellationEntityVersion "anterior commissure" from WHSSD v2 as the whole thing - which it is not. It is just a part of the whole thing, but the name does not reflect that.  
I'm just worried that renaming them in SANDS will lead to equally many confusions the other way around. So, that users would wonder why we the PEV is called "anterior commissure, intrabulbar part" but points to the annotation/label file where it is called "anterior commissure". 

So, maybe the best way to solve this is to add a property to the schemas, @lzehl? Either something like an "internalName" next to the "name" ("internalName" = "anterior commisure", "name" = "anterior commissure, intrabulbar part") or simply a "description" where discrepancies could be explained?

**Comment by lzehl** [comment]
this issue also came up for the julich-brain atlas and other atlases. How about:

Adding "definition" (optional) that gives meaning to the term would be in any case beneficial and in principle a requirement for a proper terminology. I would argue that such a definition would be version-independent. 

Adding a "internalName" to a PEV would be also beneficial in case refinements/corrections are made for SANDS explicitly that cannot be corrected in a published dataset (without changing the version). I would just turn the logic around and specify the refinement/correction in an optional field ("correctedName") and keep the given internal name as requirement (name). The PE should use the corrected name as name and can also be updated in case of refinement over time (without changing the `@id`).

In addition I would suggest an optional "alternativeName" property for PEs and PEVs (with potential inheritance application) and an optional "additionalRemarks" property for the PEVs (to explain name corrections).

How does that sound? @UlrikeS91 & @MaaikevS

**Comment by lzehl** [comment]
This issue was solved / implemented in #169
