### ISSUE TITLE
AnatomicalLocation schema - additional revision needed

### ISSUE THREAD

**Issue by UlrikeS91** [openMetadataInitiative/openMINDS_SANDS#181]
This relates to PR #179 and the many many issue raised in other repos related to that. 

@skoehnen ask offline about a use case, where an annotation is made in an atlas (coordinate space). This annotation is a point (x,y,z) in the coordinate space and a user may want to add some sort of label/name to it to distinguish between different point more easily. 

I think that I raise in one of the issues that we should make the schema that is proposed in #179 more generic, basically removing any of the "target" references. This way a property in one schema could be called "targetLocation" (e.g. for stereotactic surgery, electrode placements, etc.) for describing what location the researcher was aiming for, while in another schema the property could be called something else (e.g. for injection sites that were annotated in the images following all the histological steps) for describing which location it really was in the end. 
To me, @skoehnen use case would be possible to capture with this schema as well. We do not have anything else that would fit this otherwise. The best compromise would have been "CustomAnatomicalEntity" which has a "CustomAnnotation" but these annotations do not match the type of annotation that he would like to capture. 

My proposal for the revision is the following:

```json
{
    "_type": "https://openminds.ebrains.eu/sands/AnatomicalLocation",
    "required": [
        "anatomicalEntity",
        "targetIdentificationType"
    ],
    "properties": {
        "anatomicalEntity": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "_instruction": "Add the anatomical entity(s) for this anatomical location.",
            "_linkedTypes": [
                "https://openminds.ebrains.eu/sands/ParcellationEntity",
                "https://openminds.ebrains.eu/sands/ParcellationEntityVersion",
                "https://openminds.ebrains.eu/sands/CustomAnatomicalEntity",
                "https://openminds.ebrains.eu/controlledTerms/CellType",
                "https://openminds.ebrains.eu/controlledTerms/UBERONParcellation"
            ]
        },
        "identificationType": {
            "_instruction": "Add the identification type used to get to this anatomical location.",
            "_linkedTypes": [
                "https://openminds.ebrains.eu/controlledTerms/AnatomicalIdentificationType"
            ]
        },
        "coordinates": {
            "_instruction": "If possible, add the coordinates that best represent this anatomical location.",
            "_embeddedTypes": [
                "https://openminds.ebrains.eu/sands/CoordinatePoint"
            ]
        },
        "additionalRemarks": {
            "type": "string",
            "_instruction": "Enter any additional remarks that are needed to interpret the properties of this anatomical location (e.g., what the coordinates represent: a central position, bottom, left corner edge, etc)."
        },
        "lookupLabel": {
           "type": "string",
           "_instruction": "Enter a lookup label for this anatomical location that may help you to more easily find it again."
        }
    }
}
```

Note: This is a bit of a mix of topics. The PR #179 should be revised to be more generic. This may not be the perfect fit for @skoehnen use case, but the schema is needed regardless of that. @skoehnen use case may be solve by this schema, then we don't have a problem. But if not, then we need to discuss other SANDS schemas instead (either the annotation schemas to allow more annotation types or the coordinatePoint to have a lookupLabel or a new schema for custom point annotations or whatever). 

@lzehl what do you think? Please also tag more people, I was not sure who else be useful to include...

FYI @Peyman-N

**Comment by lzehl** [comment]
@UlrikeS91 & @skoehnen thanks for raising the issue. I disagree a bit though

The "CustomAnatomicalEntity" which has a "CustomAnnotation" was exactly meant for the use case you describe. 
But so far we only covered the use case in the annotation schemas in general (custom or atlas) where the annotation is a volume or area. Annotations should cover though points, vectors etc as well. (everything you "draw" onto something for some reason).

For this reason I want to rather adapt the annotation schemas to cover all use cases. I need to think this a bit over before I make a counter suggestion.

**Comment by lzehl** [comment]
is now discussed here #183
