### ISSUE TITLE
New Julich-Brain Atlas Parcellation

### ISSUE THREAD

**Issue by szafarnia** [openMetadataInitiative/openMINDS_SANDS#188]
Dear all, 

Could you please add following parcellation of Julich-Brain Atlas to KG?
Area MFG2 (MFG): cerebral cortex/frontal lobe/fronto-marginal sulcus (middle frontal gyrus area 1)
Area MFG1 (MFG): cerebral cortex/frontal lobe/middle frontal gyrus (middle frontal gyrus area 1)
Area SFS1 (SFS): cerebral cortex/frontal lobe/superior frontal sulcus (superior frontal sulcus area 1)
Area SFS2 (SFS): cerebral cortex/frontal lobe/superior frontal sulcus (superior frontal sulcus area 2)

As Info: In the KGE, I already added these parcellation as “Term Suggestion”.

Many thanks in advance.

Best,
Sara

**Comment by lzehl** [comment]
@szafarnia thank you for this issue, but this issue should go to openMINDS_SANDS (I will move it now). For the future, could you register issues for atlas brain regions in SANDS and in the EBRAINS KG make suggestions for brain regions of atlases via "custom anatomical entity" instead of "term suggestion"?

**Comment by szafarnia** [comment]
@lzehl Thank you for your feedback and information. 
Should I remove these terms from “term suggestion” and register them via "custom anatomical entity"?

**Comment by lzehl** [comment]
yes if you like you can do this cleanup already

**Comment by szafarnia** [comment]
@lzehl Following Julich-Brain regions are now registered via "custom anatomical entity":
- JBA_Area-MFG1
- JBA_Area-MFG2
- JBA_Area-SFS1
- JBA_Area-SFS2
- JBA_AStr (amygdala)

Unfortunately, I'm not able to delete these entries from the "Term Suggestion"!

**Comment by lzehl** [comment]
@szafarnia at least the Parcellation Entities for these areas are now registered and should appear for usage in EBRAINS latest tomorrow. The Parcellation Entity Versions I will register with the upcoming atlas release.
