### ISSUE TITLE
"Has parent" of Brodmann Parcellation Entities not resolvable

### ISSUE THREAD

**Issue by olinux** [openMetadataInitiative/openMINDS_SANDS#190]
It seems like in Brodmann, there are several "hasParent" ids registered which are not existing. Is this going to be added at some point? 

Example:

https://github.com/HumanBrainProject/openMINDS_SANDS/blob/1f74a881877c78682c40367815e056b0c49dceef/instances/atlas/parcellationEntityVersion/Brodmann_1909/BA_1909_area1.jsonld#L10

**Comment by lzehl** [comment]
@olinux thanks for raising this issue. the correcting PR (#195) is on its way
