### ISSUE TITLE
DWMA parcellation entity instances not following a consistent id pattern

### ISSUE THREAD

**Issue by olinux** [openMetadataInitiative/openMINDS_SANDS#191]
The DWMA parcellation entity instances don't follow a consistent id pattern - please see the difference in the camelcase writing of the ParcellationEntity section. this leads to non-resolvable references.

https://github.com/HumanBrainProject/openMINDS_SANDS/blob/1f74a881877c78682c40367815e056b0c49dceef/instances/atlas/parcellationEntityVersion/DWMA_2018/DWMA_2018_externalCapsule_right.jsonld#L10

**Comment by lzehl** [comment]
@olinux thanks for raising the issue. the PR #196 should solve this issue.
