### ISSUE TITLE
Q: Adding stereotaxic coordinate systems, would there be two coordinate systems per hemisphere? 

### ISSUE THREAD

**Issue by aeidi89** [openMetadataInitiative/openMINDS_SANDS#277]
Hi,

I am working on adding the Larry Swanson Brain Maps v3 rat brain atlas and have run into some interesting questions regarding the coordinate system.

In brief, Swanson writes that he operates with two coordinate systems, one for the specimen [the physical brain tissue] and a stereotaxic (stereotactic) coordinate system, as describe by Paxinos and Watson, 1982. As far as I understand it, a stereotaxic coordinate system have one of two origins, Bregma or the Interaural point. And it seems that the direction for the left-right plan goes from the midline [of the brain] to either the left or right side of the brain.

Does this mean that there will be two coordinate systems (origin in Bregma and Interaural point respectively) for each hemisphere?

In advance, thank you for considering this question.

**Comment by lzehl** [comment]
Bregma and Interaural are used as different origins. This means that the Swanson Stereotactic Brain is definitely separated into two alternative versions.

For the left-right plane would be additionally registered into the two directions: 
LAD (left, anterior, dorsal) and RAD (right, anterior, dorsal) 

So indeed we would register 4 alternative common coordinate spaces for the Paxinos

**Comment by aeidi89** [comment]
Thank you for your answer!
